---
plugin: openapi
specFile: https://raw.githubusercontent.com/wazuh/wazuh/v4.3.1/api/api/spec/spec.yaml

resources:
  - path: /security/user/authenticate
    method: get
    response:
      statusCode: 200
      scriptFile: login.js

