# Wazuh App Copyright (C) 2021 Wazuh Inc. (License GPLv2)
version: '3.9'

x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://host.docker.internal:3100/loki/api/v1/push"

services:
  exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
    <<: *logging
    hostname: "exporter-kbn-${WAZUH_STACK}"
    networks:
      - wzd-pre
      - mon
    command:
      - '--es.uri=https://admin:SecretPassowrd@wazuh.indexer:9200'
      - '--es.ssl-skip-verify'
      - '--es.all'

  imposter:
    image: outofcoffee/imposter
    hostname: "imposter-kbn-${WAZUH_STACK}"
    networks:
      - wzd-pre
      - mon
    <<: *logging
    environment:
      - JAVA_OPTS="-Xmx512m -Xss512k -Dfile.encoding=UTF-8 -XX:MaxRAM=800m -XX:MaxRAMPercentage=95 -XX:MinRAMPercentage=60A"
      - MALLOC_ARENA_MAX=1
    volumes:
      - ./config/imposter:/opt/imposter/config

  generator:
    image: wazuh/wazuh-certs-generator:0.0.1
    hostname: wazuh-certs-generator
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/certificates/
      - ./config/certs.yml:/config/certs.yml
    # hack to fix permissions of the certificates
    healthcheck:
      test: ["CMD-SHELL", "chmod 755 /certificates && chmod 644 /certificates/* && [ -f certificates/wazuh.indexer.pem ]"]
      interval: 1s
      timeout: 5s
      retries: 120

  filebeat:
    depends_on:
      wazuh.indexer.tester:
        condition: service_healthy
    image: elastic/filebeat:7.10.2
    hostname: filebeat
    user: "0:0"
    networks:
      - wzd-pre
    <<: *logging
    restart: always
    entrypoint:
      - '/bin/bash'
    command: >
      -c '
        mkdir -p /etc/filebeat
        echo admin | filebeat keystore add username --stdin --force
        echo SecretPassword| filebeat keystore add password --stdin --force
        curl -so /etc/filebeat/wazuh-template.json https://raw.githubusercontent.com/wazuh/wazuh/4.3/extensions/elasticsearch/7.x/wazuh-template.json
        curl -s https://packages.wazuh.com/4.x/filebeat/wazuh-filebeat-0.2.tar.gz | tar -xvz -C /usr/share/filebeat/module
        filebeat setup -e
        filebeat
      '
    volumes:
      - ./config/wazuh_indexer_ssl_certs/:/etc/ssl/wazuh
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml


  wazuh.indexer:
    depends_on:
      generator:
        condition: service_healthy
    image: wazuh/wazuh-indexer:${WAZUH_STACK}
    hostname: wazuh.indexer
    networks:
      - wzd-pre
    <<: *logging
    restart: always
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/config/certs/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.key
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/config/certs/wazuh.indexer.pem
      - ./config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/config/certs/admin.pem
      - ./config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/config/certs/admin-key.pem
      - ./config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/config/opensearch.yml
      - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/internal_users.yml

  wazuh.indexer.tester:
    image: curlimages/curl
    entrypoint: '/bin/sh'
    <<: *logging
    networks:
      - wzd-pre
    command: >
      -c '
       cat
       '
    volumes:
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/tmp/root-ca.pem
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert /tmp/root-ca.pem https://wazuh.indexer:9200 | grep -q 'missing authentication credentials'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120


  wazuh.dashboard:
    image: wazuh/wazuh-dashboard:${WAZUH_STACK}
    hostname: wazuh.dashboard
    depends_on:
      wazuh.indexer.tester:
        condition: service_healthy
    networks:
      - wzd-pre
    <<: *logging
    restart: always
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=http://imposter:8080
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    volumes:
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - ./config/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - ./config/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
    depends_on:
      - wazuh.indexer

networks:
  networks:
  wzd-pre:
    name: wzd-pre-${WAZUH_STACK}
    driver: bridge
  mon:
    external: true

volumes:
  wazuh_api_configuration:
  wazuh_etc:
  wazuh_logs:
  wazuh_queue:
  wazuh_var_multigroups:
  wazuh_integrations:
  wazuh_active_response:
  wazuh_agentless:
  wazuh_wodles:
  filebeat_etc:
  filebeat_var:
  wazuh-indexer-data:

